define(
	function() {
		'use strict';
		
		window.langCode = 'en';
		window.LANGMAPEN = {
		    "CORE" : "core",
		    "CORE.BOOTSTRAPPER" : "",
		    "CORE.BOOTSTRAPPER.ERRORS" : "",
		    "CORE.BOOTSTRAPPER.ERRORS.DEFAULT" : "",
		    "CORE.BOOTSTRAPPER.ERRORS.DEFAULT.DESCRIPTION" : "The requested action failed due to server error. Please contact your system administrator or view the Event Log on the server.",
		    "CORE.BOOTSTRAPPER.ERRORS.DEFAULT.TITLE" : "Internal Server Error",
		    "CORE.DEMO" : "demo",
		    "CORE.DEMO.CASES" : "cases",
		    "CORE.DEMO.CASES.OTHER" : "other",
		    "CORE.DEMO.CASES.OTHER.LOCALIZATIONSERVICE" : "Demo Text",
		    "CORE.DEMO.CASES.OTHER.LOCALIZATIONSERVICE.DAYSPLURAL" : "day,days",
		    "CORE.FORM" : "form",
		    "CORE.FORM.EDITORS" : "editors",
		    "CORE.FORM.EDITORS.COLLECTION" : "collection",
		    "CORE.FORM.EDITORS.COLLECTION.ADDNEWITEM" : "Add a new item",
		    "CORE.FORM.EDITORS.COLLECTION.EMPTYCOLLECTION" : "You need to create record before adding values to the table",
		    "CORE.FORM.EDITORS.DATE" : "date",
		    "CORE.FORM.EDITORS.DATE.DISABLEDPLACEHOLDER" : "Field is disabled",
		    "CORE.FORM.EDITORS.DATE.EMPTYPLACEHOLDER" : "Date",
		    "CORE.FORM.EDITORS.DATE.READONLYPLACEHOLDER" : "Field is read-only",
		    "CORE.FORM.EDITORS.DROPDOWN" : "dropdown",
		    "CORE.FORM.EDITORS.DROPDOWN.NOTSET" : "Not set",
		    "CORE.FORM.EDITORS.DROPDOWN.SEARCH" : "Search...",
		    "CORE.FORM.EDITORS.DURATION" : "",
		    "CORE.FORM.EDITORS.DURATION.NOTSET" : "Not set",
		    "CORE.FORM.EDITORS.DURATION.WORKDURATION" : "",
		    "CORE.FORM.EDITORS.DURATION.WORKDURATION.DAYS" : " d",
		    "CORE.FORM.EDITORS.DURATION.WORKDURATION.DAYS.SEPARATORCHAR" : "d",
		    "CORE.FORM.EDITORS.DURATION.WORKDURATION.HOURS" : " h",
		    "CORE.FORM.EDITORS.DURATION.WORKDURATION.HOURS.PREFIX" : " ",
		    "CORE.FORM.EDITORS.DURATION.WORKDURATION.HOURS.SEPARATORCHAR" : "h",
		    "CORE.FORM.EDITORS.DURATION.WORKDURATION.MINUTES" : " m",
		    "CORE.FORM.EDITORS.DURATION.WORKDURATION.MINUTES.PREFIX" : " ",
		    "CORE.FORM.EDITORS.DURATION.WORKDURATION.SECONDS" : " s",
		    "CORE.FORM.EDITORS.DURATION.WORKDURATION.SECONDS.PREFIX" : " ",
		    "CORE.FORM.EDITORS.MENTIONS" : "mentions",
		    "CORE.FORM.EDITORS.MENTIONS.PLACEHOLDER" : "Enter text here. Use @ to notify others",
		    "CORE.FORM.EDITORS.MULTISELECT" : "",
		    "CORE.FORM.EDITORS.MULTISELECT.ANYTHINGSELECTED" : "Few items selected",
		    "CORE.FORM.EDITORS.MULTISELECT.APPLY" : "Apply",
		    "CORE.FORM.EDITORS.MULTISELECT.CANCEL" : "Cancel",
		    "CORE.FORM.EDITORS.MULTISELECT.CLOSE" : "Close",
		    "CORE.FORM.EDITORS.MULTISELECT.EVERYTHINGSELECTED" : "All items selected",
		    "CORE.FORM.EDITORS.MULTISELECT.NOTHINGSELECTED" : "No items selected",
		    "CORE.FORM.EDITORS.MULTISELECT.RESET" : "Reset",
		    "CORE.FORM.EDITORS.MULTISELECT.SELECTALL" : "Select all",
		    "CORE.FORM.EDITORS.NUMBER" : "number",
		    "CORE.FORM.EDITORS.NUMBER.NOTSETPLACEHOLDER" : "Not set",
		    "CORE.FORM.EDITORS.PASSWORD" : "password",
		    "CORE.FORM.EDITORS.PASSWORD.PLACEHOLDER" : "Enter password",
		    "CORE.FORM.EDITORS.TEXTAREAEDITOR" : "textAreaEditor",
		    "CORE.FORM.EDITORS.TEXTAREAEDITOR.DISABLEPLACEHOLDER" : "Field is disabled",
		    "CORE.FORM.EDITORS.TEXTAREAEDITOR.PLACEHOLDER" : "Enter text here",
		    "CORE.FORM.EDITORS.TEXTAREAEDITOR.READONLYPLACEHOLDER" : "Field is read-only",
		    "CORE.FORM.EDITORS.TEXTEDITOR" : "textEditor",
		    "CORE.FORM.EDITORS.TEXTEDITOR.DISABLEPLACEHOLDER" : "Field is disabled",
		    "CORE.FORM.EDITORS.TEXTEDITOR.PLACEHOLDER" : "Enter text here",
		    "CORE.FORM.EDITORS.TEXTEDITOR.READONLYPLACEHOLDER" : "Field is read-only",
		    "CORE.FORM.EDITORS.TIME" : "time",
		    "CORE.FORM.EDITORS.TIME.DISABLEDPLACEHOLDER" : "Field is disabled",
		    "CORE.FORM.EDITORS.TIME.EMPTYPLACEHOLDER" : "Time",
		    "CORE.FORM.EDITORS.TIME.READONLYPLACEHOLDER" : "Field is read-only",
		    "CORE.FORM.VALIDATION" : "",
		    "CORE.FORM.VALIDATION.LENGTH" : "Wrong number of characters.",
		    "CORE.FORM.VALIDATION.LETTERS" : "Only letters are allowed.",
		    "CORE.FORM.VALIDATION.PASSWORD" : "Password must be at least 8 characters long.",
		    "CORE.FORM.VALIDATION.PHONE" : "Phone number must be at least 8 characters long. <br> Use digits and characters (), -, +.",
		    "CORE.FORM.VALIDATION.REQUIRED" : "This field is required.",
		    "CORE.FORM.VALIDATION.SYSTEMNAME" : "The system name contains invalid characters.",
		    "CORE.FORMATS" : "formats",
		    "CORE.FORMATS.DATETIME" : "datetime",
		    "CORE.FORMATS.DATETIME.DAYSFULL" : "Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",
		    "CORE.FORMATS.DATETIME.DAYSSHORT" : "Sun,Mon,Tue,Wed,Thu,Fri,Sat",
		    "CORE.FORMATS.DATETIME.MERIDIEM" : "AM,PM",
		    "CORE.FORMATS.DATETIME.MONTHS" : "January,February,March,April,May,June,July,August,September,October,November,December",
		    "CORE.FORMATS.DATETIME.MONTHSSHORT" : "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
		    "CORE.FORMATS.DATETIME.TODAY" : "Today",
		    "CORE.GRID" : "grid",
		    "CORE.GRID.CELLVIEWFACTORY" : "",
		    "CORE.GRID.CELLVIEWFACTORY.BOOLEANCELLVIEW" : "",
		    "CORE.GRID.CELLVIEWFACTORY.BOOLEANCELLVIEW.NO" : "No",
		    "CORE.GRID.CELLVIEWFACTORY.BOOLEANCELLVIEW.YES" : "Yes",
		    "CORE.GRID.EMPTYVIEW" : "",
		    "CORE.GRID.EMPTYVIEW.EMPTY" : "The list is empty",
		    "CORE.GRID.LOADINGROW" : "loadingRow",
		    "CORE.GRID.LOADINGROW.LOADING" : "LOADING",
		    "CORE.GRID.NOCOLUMNSVIEW" : "noColumnsView",
		    "CORE.GRID.NOCOLUMNSVIEW.ALLCOLUMNSHIDDEN" : "All columns are hidden",
		    "CORE.SERVICES" : "",
		    "CORE.SERVICES.LOCALIZATION" : "",
		    "CORE.SERVICES.LOCALIZATION.PLURALFORM" : "(n != 1)",
		    "CORE.SERVICES.MESSAGE" : "",
		    "CORE.SERVICES.MESSAGE.BUTTONS" : "",
		    "CORE.SERVICES.MESSAGE.BUTTONS.NO" : "No",
		    "CORE.SERVICES.MESSAGE.BUTTONS.OK" : "ok",
		    "CORE.SERVICES.MESSAGE.BUTTONS.RETURN" : "Return to start page",
		    "CORE.SERVICES.MESSAGE.BUTTONS.YES" : "Yes",
		    "CORE.SERVICES.MESSAGE.DESCRIPTION" : "",
		    "CORE.SERVICES.MESSAGE.DESCRIPTION.ACCESSDENIEDDESCRIPTION" : "You don’t have access to this section. Please contact your system administrator.",
		    "CORE.SERVICES.MESSAGE.TITLE" : "",
		    "CORE.SERVICES.MESSAGE.TITLE.ACCESSDENIED" : "Access denied",
		    "CORE.SERVICES.MESSAGE.TITLE.CONFIRMATION" : "Warning",
		    "CORE.SERVICES.MESSAGE.TITLE.ERROR" : "Error",
		    "CORE.VIEWS" : "",
		    "CORE.VIEWS.BEHAVIORS" : "",
		    "CORE.VIEWS.BEHAVIORS.LOADING" : "",
		    "CORE.VIEWS.BEHAVIORS.LOADING.DEFAULTLOADINGSMALL" : "Loading",
		    "CORE.VIEWS.SEARCHBAR" : "",
		    "CORE.VIEWS.SEARCHBAR.PLACEHOLDER" : "Start typing to get suggestions",
		};
	}
);
